#!/bin/sh

SENSITIVE_DIR=SNS_CHANGE_ME
QWT_DIR=QWT_CHANGE_ME
SN_DIR=SN_CHANGE_ME

LD_LIBRARY_PATH="${SENSITIVE_DIR}/lib;${QWT_DIR};${SN_DIR}"; export LD_LIBRARY_PATH

cd ${SENSITIVE_DIR}/bin
./Inversitive_UI.bin
